---
name: itsm_processing_incs_check
pack: ntt_itsm
description: "Get a list of processing ITSM incidents from the kv store and check if they are still open"
enabled: true

trigger:
  type: "core.st2.CronTimer"
  # http://apscheduler.readthedocs.io/en/3.0/modules/triggers/cron.html#api
  parameters:
      timezone: "UTC"
      day_of_week: "*"
      # 12pm noon EST
      hour: 16
      minute: 0
      second: 0

action:
  ref: "ntt_itsm.itsm_processing_incs_check"
